[package]
name = "bogglesolver"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
